---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Niklas.
--- DateTime: 8/24/2022 4:53 PM
---

local Decode = require("Decode")

return {
     ["break"] = Decode([[
        break
     ]])
}

