---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Niklas.
--- DateTime: 8/24/2022 4:53 PM
---

local Decode = require("Decode")

return {
    ["PrintArray"] = Decode([[
        add 1 r2

        arr idx r1 r2
        prt acc ::END

        arr sze r1
        com r2 < acc goto PrintArray
    ]]),

     ["sqrt"] = Decode([[
         
     ]])
}